// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package mysql

import (
	"database/sql"
	"time"
)

type Client struct {
	ClientID               int32          `json:"client_id"`
	ClientLastName         sql.NullString `json:"client_last_name"`
	ClientFirstName        sql.NullString `json:"client_first_name"`
	ClientEmail            sql.NullString `json:"client_email"`
	ClientPhone            sql.NullString `json:"client_phone"`
	ClientFiscalYearIncome sql.NullInt32  `json:"client_fiscal_year_income"`
	ClientDateCreated      sql.NullTime   `json:"client_date_created"`
}

// Client after sale service table
type ClientsAss struct {
	CaID               int32          `json:"ca_id"`
	CaClientID         sql.NullInt32  `json:"ca_client_id"`
	CaCompanyID        sql.NullInt32  `json:"ca_company_id"`
	CaCallDate         sql.NullTime   `json:"ca_call_date"`
	CaCallReason       sql.NullString `json:"ca_call_reason"`
	CaInterventionDate sql.NullTime   `json:"ca_intervention_date"`
	CaComment          sql.NullString `json:"ca_comment"`
	CaIsResolved       sql.NullBool   `json:"ca_is_resolved"`
}

type ClientsHome struct {
	ChID               int32           `json:"ch_id"`
	ChClientID         sql.NullInt32   `json:"ch_client_id"`
	ChGeoID            sql.NullInt32   `json:"ch_geo_id"`
	ChConstructionYear sql.NullInt32   `json:"ch_construction_year"`
	ChArea             sql.NullInt32   `json:"ch_area"`
	ChResidents        sql.NullInt32   `json:"ch_residents"`
	ChRoofPositionning sql.NullString  `json:"ch_roof_positionning"`
	ChRoofSlope        sql.NullInt32   `json:"ch_roof_slope"`
	ChLabel            sql.NullString  `json:"ch_label"`
	ChTr               sql.NullInt32   `json:"ch_tr"`
	ChHuc              sql.NullFloat64 `json:"ch_huc"`
	ChIsolation        sql.NullString  `json:"ch_isolation"`
}

type ClientsHomesBill struct {
	ChbID          int32         `json:"chb_id"`
	ChbHomeID      sql.NullInt32 `json:"chb_home_id"`
	ChbElectricity sql.NullInt32 `json:"chb_electricity"`
	ChbNaturalGas  sql.NullInt32 `json:"chb_natural_gas"`
	ChbPropaneGas  sql.NullInt32 `json:"chb_propane_gas"`
	ChbWood        sql.NullInt32 `json:"chb_wood"`
	ChbHeatingOil  sql.NullInt32 `json:"chb_heating_oil"`
	ChbYear        sql.NullInt32 `json:"chb_year"`
}

type ClientsHomesEquipment struct {
	CheID            int32          `json:"che_id"`
	CheHomeID        sql.NullInt32  `json:"che_home_id"`
	CheEquipmentType sql.NullString `json:"che_equipment_type"`
	CheDescription   sql.NullString `json:"che_description"`
}

type ClientsInstallation struct {
	CiID           int32          `json:"ci_id"`
	CiClientID     sql.NullInt32  `json:"ci_client_id"`
	CiUserID       sql.NullInt32  `json:"ci_user_id"`
	CiSharedUserID sql.NullInt32  `json:"ci_shared_user_id"`
	CiCreationDate sql.NullTime   `json:"ci_creation_date"`
	CiUpdateDate   sql.NullTime   `json:"ci_update_date"`
	CiStatus       sql.NullString `json:"ci_status"`
	CiComments     sql.NullString `json:"ci_comments"`
}

type ClientsInstallationsFile struct {
	CifID               int32          `json:"cif_id"`
	CifInstallationID   sql.NullInt32  `json:"cif_installation_id"`
	CifFileType         sql.NullString `json:"cif_file_type"`
	CifFileUrl          sql.NullString `json:"cif_file_url"`
	CifFileCreationDate sql.NullTime   `json:"cif_file_creation_date"`
}

type ClientsInstallationsPayment struct {
	CipID                int32           `json:"cip_id"`
	CipInstallationID    sql.NullInt32   `json:"cip_installation_id"`
	CipAmount            sql.NullFloat64 `json:"cip_amount"`
	CipType              sql.NullString  `json:"cip_type"`
	CipDate              sql.NullTime    `json:"cip_date"`
	CipDescription       sql.NullString  `json:"cip_description"`
	CipTransactionNumber sql.NullString  `json:"cip_transaction_number"`
	CipVatRate           sql.NullFloat64 `json:"cip_vat_rate"`
}

type ClientsInstallationsProduct struct {
	CipID             int32          `json:"cip_id"`
	CipInstallationID sql.NullInt32  `json:"cip_installation_id"`
	CipProductID      sql.NullInt32  `json:"cip_product_id"`
	CipDiscount       sql.NullString `json:"cip_discount"`
}

type ClientsLoan struct {
	ClID               int32           `json:"cl_id"`
	ClClientID         sql.NullInt32   `json:"cl_client_id"`
	ClAmount           sql.NullFloat64 `json:"cl_amount"`
	ClInstallments     sql.NullFloat64 `json:"cl_installments"`
	ClClientProvision  sql.NullFloat64 `json:"cl_client_provision"`
	ClClientPrepayment sql.NullFloat64 `json:"cl_client_prepayment"`
	ClInsured          sql.NullInt32   `json:"cl_insured"`
	ClFundingAgency    sql.NullString  `json:"cl_funding_agency"`
}

type Company struct {
	CID           int32          `json:"c_id"`
	CGeoID        sql.NullInt32  `json:"c_geo_id"`
	CName         sql.NullString `json:"c_name"`
	CRcs          sql.NullString `json:"c_rcs"`
	CSiret        sql.NullString `json:"c_siret"`
	CSiren        sql.NullString `json:"c_siren"`
	CIntraEuVat   sql.NullString `json:"c_intra_eu_vat"`
	CLegalStatus  sql.NullString `json:"c_legal_status"`
	CCreationDate sql.NullString `json:"c_creation_date"`
	CCapital      sql.NullInt32  `json:"c_capital"`
}

type EnergiesCost struct {
	EncID   int32          `json:"enc_id"`
	EncType sql.NullString `json:"enc_type"`
	EncDate sql.NullTime   `json:"enc_date"`
	EncCost sql.NullString `json:"enc_cost"`
}

type EquipmentsCatalogue struct {
	EcID          int32          `json:"ec_id"`
	EcProductID   sql.NullInt32  `json:"ec_product_id"`
	EcQuantity    sql.NullInt32  `json:"ec_quantity"`
	EcDescription sql.NullString `json:"ec_description"`
	EcDateAdded   sql.NullTime   `json:"ec_date_added"`
	EcDateUpdated sql.NullTime   `json:"ec_date_updated"`
}

type EquipmentsCategory struct {
	EcID           int32          `json:"ec_id"`
	EcCategoryCode sql.NullString `json:"ec_category_code"`
	EcDescription  sql.NullString `json:"ec_description"`
}

type EquipmentsDesignation struct {
	EaID          int32          `json:"ea_id"`
	EaProductID   sql.NullInt32  `json:"ea_product_id"`
	EaArticle     sql.NullString `json:"ea_article"`
	EaDescription sql.NullString `json:"ea_description"`
	EaTitle       sql.NullString `json:"ea_title"`
}

type EquipmentsInstaller struct {
	EiID        int32         `json:"ei_id"`
	EiProductID sql.NullInt32 `json:"ei_product_id"`
	EiCompanyID sql.NullInt32 `json:"ei_company_id"`
}

type EquipmentsProduct struct {
	EpID                int32          `json:"ep_id"`
	EpProductID         sql.NullInt32  `json:"ep_product_id"`
	EpPrice             sql.NullString `json:"ep_price"`
	EpVat               sql.NullString `json:"ep_vat"`
	EpInstallationPrice sql.NullString `json:"ep_installation_price"`
}

type EquipmentsService struct {
	EsID          int32          `json:"es_id"`
	EsDescription sql.NullString `json:"es_description"`
	EsPrice       sql.NullString `json:"es_price"`
}

type Geo struct {
	ChgID         int32           `json:"chg_id"`
	ChgZone       sql.NullString  `json:"chg_zone"`
	ChgLatitude   sql.NullFloat64 `json:"chg_latitude"`
	ChgLongitude  sql.NullFloat64 `json:"chg_longitude"`
	ChgAltitude   sql.NullInt32   `json:"chg_altitude"`
	ChgDepartment sql.NullInt32   `json:"chg_department"`
	ChgCity       sql.NullString  `json:"chg_city"`
	ChgAddress    sql.NullString  `json:"chg_address"`
	ChgPostcode   sql.NullInt32   `json:"chg_postcode"`
}

type Group struct {
	GID          int32          `json:"g_id"`
	GName        sql.NullString `json:"g_name"`
	GDescription sql.NullString `json:"g_description"`
}

type GroupsPrivilege struct {
	GpPrivilegeID int32          `json:"gp_privilege_id"`
	GpPrivilege   sql.NullString `json:"gp_privilege"`
}

type GroupsPrivilegesLnk struct {
	GplID          int32         `json:"gpl_id"`
	GplGroupID     sql.NullInt32 `json:"gpl_group_id"`
	GplPrivilegeID sql.NullInt32 `json:"gpl_privilege_id"`
}

type GroupsUsersLnk struct {
	GuID      int32         `json:"gu_id"`
	GuUserID  sql.NullInt32 `json:"gu_user_id"`
	GuGroupID sql.NullInt32 `json:"gu_group_id"`
}

type Log struct {
	LogID        int32          `json:"log_id"`
	LogEventDesc sql.NullString `json:"log_event_desc"`
	LogEventCode sql.NullString `json:"log_event_code"`
	LogEventDate sql.NullTime   `json:"log_event_date"`
}

type SalesCommission struct {
	ScID                    int32         `json:"sc_id"`
	ScCommissionsDiscountID sql.NullInt32 `json:"sc_commissions_discount_id"`
	ScGroupID               sql.NullInt32 `json:"sc_group_id"`
}

type SalesCommissionsDiscount struct {
	ScID          int32           `json:"sc_id"`
	ScDiscountPct sql.NullFloat64 `json:"sc_discount_pct"`
	ScComPct      sql.NullFloat64 `json:"sc_com_pct"`
}

type User struct {
	UserID              int32          `json:"user_id"`
	UserFirstname       sql.NullString `json:"user_firstname"`
	UserLastname        sql.NullString `json:"user_lastname"`
	UserEmail           sql.NullString `json:"user_email"`
	UserPhone           sql.NullString `json:"user_phone"`
	UserIsActive        sql.NullBool   `json:"user_is_active"`
	UserDateCreated     time.Time      `json:"user_date_created"`
	UserRecruitmentDate sql.NullTime   `json:"user_recruitment_date"`
}
